### ISSUE TITLE
KeyError COMP_WORDS

### ISSUE THREAD

**Issue by develmaycare** [develmaycare/pyprojectutils#21]
Attempting to implement #15, `project_list_autocomplete()` for `bumpversion` is issuing a ``KeyError``.

```
Traceback (most recent call last):
  File "./bumpversion.py", line 12, in <module>
    sys.exit(version_update())
  File "../pyprojectutils/cli.py", line 911, in version_update
    project_list_autocomplete()
  File "../pyprojectutils/cli.py", line 21, in project_list_autocomplete
    cwords = os.environ['COMP_WORDS'].split()[1:]
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'COMP_WORDS'
```

**Comment by develmaycare** [comment]
I'm not familiar enough with how this works to grok the reason for the error. What I know is:

1. I used Django's management command autocomplete as an example.
2. I copied the `django-autocomplete.bash` as is.
3. The `project_list_autocomplete()` function is being called. So at least one environment variable in `pyprojectutils-autocomplete.bash` is being set.

Yet it isn't working.
